server:
  port : 8761

eureka:
  instance:
    hostname : localhost
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone : http://localhost:9761/eureka/
spring:
  application:
    name : eurekasvc